require('lint').linter_by_ft = {
    text = {
        'vale',
        'codespell',
        'cspell',
        'mispell',
        'proselint',
        'textlint',
    },
    tex = {
        'vale',
        'codespell',
        'cspell',
        'mispell',
        'proselint',
        'textlint',
    },
    markdown = {
        'vale',
        'alex',
        'mispell',
        'proselint',
        'textlint',
        'write-good',
        'mispell',
    },
    lua = {
        'luacheck',
        'selene',
        'codespell',
        'cspell',
    },
    python = {
        'flake8',
        'mypy',
        'pydocstyle',
        'pylama',
        'pylint',
        'pyproject-flake8',
        'pyre',
        'rstcheck',
        'ruff',
        'semgrep',
        'vulture',
        'codespell',
        'cspell',
    },
    go = {
        'golangci-lint',
        'revived',
        'semgrep',
        'staticcheck',
        'codespell',
        'cspell',
    },
    gitcommit = {
        'commitlint',
        'gitlint',
        'codespell',
        'cspell',
    },
    json = {
        'cfn-lint',
        'jsonlint',
        'semgrep',
        'codespell',
        'cspell',
    },
    sql = {
        'sqlfluff',
        'codespell',
        'cspell',
    },
    vim = {
        'vint',
        'codespell',
        'cspell',
    },
    yaml = {
        'actionlint',
        'cfn-lint',
        'yamllint',
        'codespell',
        'cspell',
    },
    c = {
        'cpplint',
        'codespell',
        'cspell',
    },
    cpp = {
        'cpplint',
        'codespell',
        'cspell',
    },
    cmake = {
        'cmakelang',
        'codespell',
        'cspell',
    },
}
